spring:
  application:
    name: nextpark

  datasource:
    url: ${AZURE_SQL_URL}
    username: ${AZURE_SQL_USER}
    password: ${AZURE_SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: ${AZURE_SQL_SCHEMA:dbo}
    locations: classpath:db/migration
    url: ${AZURE_SQL_URL}
    user: ${AZURE_SQL_USER}
    password: ${AZURE_SQL_PASSWORD}
    clean-disabled: false
    baseline-version: 0

logging:
  level:
    org.springframework.security: TRACE
