spring:
  application:
    name: nextpark

  datasource:
    url: ${azure.sql.url}
    username: ${azure.sql.user}
    password: ${azure.sql.password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: ${AZURE_SQL_SCHEMA:dbo}
    locations: classpath:db/migration
    url: ${azure.sql.url}
    user: ${azure.sql.user}
    password: ${azure.sql.password}
    clean-disabled: false
    baseline-version: 0

logging:
  level:
    org.springframework.security: TRACE
