-- TABELAS
CREATE TABLE USUARIOS (
  ID       BIGINT IDENTITY(1,1) PRIMARY KEY,
  USERNAME NVARCHAR(80)   NOT NULL UNIQUE,
  PASSWORD NVARCHAR(200)  NOT NULL,
  ROLE     NVARCHAR(20)   NOT NULL CHECK (ROLE IN ('CLIENTE','GERENTE'))
);

CREATE TABLE VAGAS (
  ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
  CODIGO NVARCHAR(20)   NOT NULL UNIQUE,
  STATUS NVARCHAR(10)   NOT NULL CHECK (STATUS IN ('LIVRE','OCUPADA'))
);

CREATE TABLE MOTOS (
  ID            BIGINT IDENTITY(1,1) PRIMARY KEY,
  PLACA         NVARCHAR(10)  NOT NULL UNIQUE,
  MODELO        NVARCHAR(80)  NOT NULL,
  STATUS        NVARCHAR(15)  NOT NULL CHECK (STATUS IN ('ALOCADA','MANUTENCAO','VISTORIA','DESALOCADA')),
  OWNER_USER_ID BIGINT        NOT NULL,
  VAGA_ID       BIGINT,
  CONSTRAINT FK_MOTOS_OWNER FOREIGN KEY (OWNER_USER_ID) REFERENCES USUARIOS(ID),
  CONSTRAINT FK_MOTOS_VAGA  FOREIGN KEY (VAGA_ID)       REFERENCES VAGAS(ID)
);

CREATE TABLE HIST_MOV (
  ID              BIGINT IDENTITY(1,1) PRIMARY KEY,
  MOTO_ID         BIGINT        NOT NULL,
  ORIGEM_VAGA_ID  BIGINT,
  DESTINO_VAGA_ID BIGINT,
  ACAO            NVARCHAR(20) NOT NULL,
  USUARIO         NVARCHAR(80) NOT NULL,
  CREATED_AT      DATETIME2     NOT NULL DEFAULT SYSDATETIME(),
  CONSTRAINT FK_HIST_MOTO   FOREIGN KEY (MOTO_ID)         REFERENCES MOTOS(ID) ON DELETE CASCADE,
  CONSTRAINT FK_HIST_ORIGEM FOREIGN KEY (ORIGEM_VAGA_ID)  REFERENCES VAGAS(ID),
  CONSTRAINT FK_HIST_DEST   FOREIGN KEY (DESTINO_VAGA_ID) REFERENCES VAGAS(ID)
);
