-- Índice para filtros por dono
BEGIN TRY
    EXEC sp_executesql N'CREATE INDEX IDX_MOTOS_OWNER ON MOTOS (OWNER_USER_ID)';
END TRY
BEGIN CATCH
    IF ERROR_NUMBER() != 2714
    BEGIN
        THROW;
    END
END CATCH;

-- Índices úteis nas FKs do histórico
BEGIN TRY
    EXEC sp_executesql N'CREATE INDEX IDX_HIST_MOTO ON HIST_MOV (MOTO_ID)';
END TRY
BEGIN CATCH
    IF ERROR_NUMBER() != 2714
    BEGIN
        THROW;
    END
END CATCH;

BEGIN TRY
    EXEC sp_executesql N'CREATE INDEX IDX_HIST_ORIGEM ON HIST_MOV (ORIGEM_VAGA_ID)';
END TRY
BEGIN CATCH
    IF ERROR_NUMBER() != 2714
    BEGIN
        THROW;
    END
END CATCH;

BEGIN TRY
    EXEC sp_executesql N'CREATE INDEX IDX_HIST_DEST ON HIST_MOV (DESTINO_VAGA_ID)';
END TRY
BEGIN CATCH
    IF ERROR_NUMBER() != 2714
    BEGIN
        THROW;
    END
END CATCH;
